//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.MedToTags = new HashSet<MedToTag>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string MedName { get; set; }
        public Nullable<System.DateTime> Prodaction { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> FirmID { get; set; }
        public Nullable<int> Amound { get; set; }
        public Nullable<byte> WithResept { get; set; }
    
        public virtual Firm Firm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedToTag> MedToTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
